### PR TITLE
Matching bounces and charges to the videos

### PR DESCRIPTION
**Pull request by rpkonz**
Hi, cool project! :)

I noticed a few of the bounces and charges displayed at the top were different from the videos. Is that expected? I’ve only looked at the one map but attempting to match the display (charge/bounce boxes) to the videos for the map bind.

### CODE REVIEW

**Comment by brandonjoe** [comment]
Ohh jesus, I haven't touched this project in forever, I've been busy with work.

**Comment by brandonjoe** [comment]
You know, Maybe I'll get back into this soon! I've been messing around with model making on my free time.... I've kind of set aside coding on the free time and looked into other stuff! I have played the new ice box map though, it's pretty cool, I'll look for some lineups on that map and maybe update the site!

**Comment by rpkonz** [comment]
I just found the site but I think it looks awesome - nice work!

**Comment by rpkonz** [comment]
Sounds good - I’d be happy to help out in any way that I can!

**Comment by brandonjoe** [comment]
Heh thanks, I'm still a very junior dev (as you an tell from the spaghetti) it was just something I felt like doing on my free time. But yea, I'll hit you up if I got any problems!

**Comment by brandonjoe** [comment]
I just pushed the changes to the site, I thought I had automatic deploys with netlify, but I guess not... I'll set that up late tonight, thanks again!

**Pull request merged**
